application: distributedpress
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /images
  static_dir: static/images
- url: /tasks/.*
  script: tasks_app.app
  login: admin
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
